### ISSUE TITLE
Usar alguna IA para generar preguntad tipo test

### ISSUE THREAD

**Issue by omiras** [IronHack-2024/blueprint-ia-request#2]
## Análisis

- Investigar que IAs podemos usar para generar preguntas tipo test
- Características interesantes debería tener esta IA
   - Gratuita
   - Interesante que puedan adjuntar trozos de código
- Con que la IA genere un array de objetos con las peguntas tipo test y nos indique cual es la correcta
- Tan solo queremos saber como usarla, pero el objetivo final es que nuestra REST API tenga un endpoint similar a este

![Image](https://github.com/user-attachments/assets/323a4c04-5f30-44e0-b549-dcf284f31aa3)

Tenéis vuestro propio repo en https://github.com/IronHack-2024/blueprint-ia-request. Podéis clonarlo y pushear los cambios en la rama **main** directamente.

[HOW TO TEST](https://github.com/IronHack-2024/blueprint-ia-request/issues/2#issuecomment-2444327628)

**Comment by omiras** [comment]
@fullstackaaronsanchezbelber Según comenta Aaron al final es consumir la API de Gemini o de Open AI. Parece que gemini no necesita tarjeta de crédito pero Open AI sí. Meta tiene la suya propia, pero hay que bajarse una app

**Comment by crimanlor** [comment]
Perfecto, Óscar ¡gracias! lo he estado mirando con @fullstackaaronsanchezbelber, y me ha compartido información interesante para poder realizar una prueba de implementación con Gemma de Gemini. Descartamos por el momento OpenAI porque el excedente de consultas con esta IA puede incurrir en gastos adicionales.

**Comment by crimanlor** [comment]
**¡Primer avance!**
Tenemos una **pequeña prueba funcional** de cómo **conectar una app de Express con la API de Gemini/Gemma**.
Hemos creado una variable prompt y generando contenido con la IA (para la que hemos tenido que adquirir previamente una API_KEY) relacionado con esta variable.
```const express = require('express');
const morgan = require('morgan');
const dotenv = require('dotenv');
dotenv.config();
const PORT = process.env.PORT || 3000;
const API_KEY = process.env.API_KEY;

const { GoogleGenerativeAI } = require("@google/generative-ai");

const app = express();

app.use(express.json());
app.use(morgan('tiny'));

app.get('/api', async (req, res) => {
    const genAI = new GoogleGenerativeAI(process.env.API_KEY);
    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

    const prompt = "Generate a multiple-choice question suitable for junior developers about Node.js.";

    const result = await model.generateContent(prompt);
    res.json(result.response.text());
})

app.listen(PORT, () => {
    console.log(`Servidor escuchando en el puerto ${PORT}`);
})
```
![Captura de pantalla 2024-10-24 a las 19 47 54](https://github.com/user-attachments/assets/ea9be949-db46-4fbe-a815-b99fd459a274)

**¡Continuamos con las pruebas!**
Para mejorar el formato de las respuestas y probar si es posible crear un array de objetos con las peguntas tipo test y que nos indique cual es la correcta.

**Comment by omiras** [comment]
El modelo de datos va a ser este :

```
const questionSchema = new Schema({
 

    question: {
        type: String,
        require: true
    },
 
    answerOptions: [
        {
          answer: {
            type: String,
            required: true // Texto de la opción de respuesta 
          },
          isCorrect: {
            type: Boolean,
            required: true // Indicación de si esta opción de respuesta es correcta 
          }
        },
        
      ], 
  

const Question = model('question', questionSchema);

module.exports = Question  . Generame un objeto que siga este modelo
```

y un ejemplo de pregutna tipo test es este:

{
  "question": "What does CSS stand for?",
  "answerOptions": [
    {
      "answer": "Cascading Style Sheets",
      "isCorrect": true
    },
    {
      "answer": "Computer Style System",
      "isCorrect": false
    },
    {
      "answer": "Creative Styling Solution",
      "isCorrect": false
    },
    {
      "answer": "Coded Style Syntax",
      "isCorrect": false
    }
  ]
}

**Comment by nidaakb** [comment]
Hoy hemos implementado los siguientes puntos:
- **Refinado** y traducido al inglés el **prompt** para poder obtener las preguntas de forma alineada con el endpoint que actualmente está siendo implementado por los compañero siguiendo el siguiente modelo:
```
{
       "question": "Question text here",
       "codeSnippet": "Add a code snippet if needed, if not leave it empty",
       "answerOptions": [
           {"answer": "Option 1", "isCorrect": boolean},
           {"answer": "Option 2", "isCorrect": boolean},
           {"answer": "Option 3", "isCorrect": boolean},
           {"answer": "Option 4", "isCorrect": boolean}
       ],
       "explanation": "Explanation here"
}
```

- Implementado en el prompt la opción de **añadir un code snippet** en caso que sea necesario y de valor añadido a la pregunta. (Más visual para el usuario) 

- **Refactorizado** la funcionalidad de **formatear la respuesta** en formato JSON para que siempre devuelva el objeto quizData del siguiente formato: 
```
{
  "quizData": {
    "question": "You are building a REST API with Node.js and Express. You need to handle a GET request to retrieve data from a database. Which middleware is commonly used to parse incoming request bodies and make the data available to your route handler?",
    "codeSnippet": "```javascript\n// Example route handler\napp.get('/users', (req, res) =\u003E {\n  // Access parsed data from request body\n  const userData = req.body;\n  // ...\n});\n```",
    "answerOptions": [
      {
        "answer": "express.json()",
        "isCorrect": true
      },
      {
        "answer": "express.static()",
        "isCorrect": false
      },
      {
        "answer": "express.urlencoded()",
        "isCorrect": false
      },
      {
        "answer": "express.router()",
        "isCorrect": false
      }
    ],
    "explanation": "The `express.json()` middleware is specifically designed to parse JSON payloads sent in the request body and attach the parsed data to the `req.body` object. This allows you to easily access and work with the data within your route handler."
  }
}
```
**Pending: Manejo de errores** 

Controlar que en caso de que la respuesta no sea en formato JSON que nos devuelva un error. Posible forma es usando un [paquete de terceros](https://www.npmjs.com/package/is-my-json-valid)

**Comment by nidaakb** [comment]
## How to test

### Preconditions:

1. Clone the [blueprint-ia-request](https://github.com/IronHack-2024/blueprint-ia-request) repo.
2. Initialise it with the command: “npm install”.
3. Add the API_KEY in the .env file. 

> To obtain the API key, please contact us directly or you can create one by following the instructions in this [doc](https://ai.google.dev/gemini-api?utm_source=google&utm_medium=cpc&utm_campaign=core-brand-eur-sem&utm_id=21341690381&gad_source=1&gclid=Cj0KCQjwj4K5BhDYARIsAD1Ly2pEYgGHlKeWUpM-dD_aLvpNXnoV6hjLCB5nOSsras8BUuGmQdbmokQaAliyEALw_wcB&hl=es-419)

### Test case 1 - Navigate to the /api Endpoint

**Action:** Open any browser of your choice and enter: `http://localhost:3000/api`

**Expected result:** A JSON response will be displayed in the following format:
```
{
  "question": "Question text here",
  "codeSnippet": "Add a code snippet if needed, if not leave it empty",
  "answerOptions": [
    {"answer": "Option 1", "isCorrect": boolean},
    {"answer": "Option 2", "isCorrect": boolean},
    {"answer": "Option 3", "isCorrect": boolean},
    {"answer": "Option 4", "isCorrect": boolean}
  ],
  "explanation": "Explanation here"
}
```
Each part of the JSON should meet the following conditions:

- `“question”`→ Should contain the question test as a string.
- `“codeSnippet”`→ Should contain a code snippet as a string, or be left empty if not needed.
- `“answerOptions”` → Should be an array of 4 objects and each object should have:
  - An `“answer”`string containing a possible answer.
  - An `“isCorrect”` boolean that should be set to true is the answer is correct or false if the answer is incorrect. → ONLY 1 correct answer.
- `“explanation”` → Should contain a string with the explanation of the correct answer.


### Test case 2 - Default topic

**Action:** Open any browser of your choice and enter: `http://localhost:3000/api` (without adding any parameter to it).

**Expected result:** The page will display a JSON using the default topic, which is set to `Node.js` in the code.

`const topic = req.query.topic || "Node.js";  `

### Test case 3 - Custom topic

**Action:** Open any browser of your choice and enter: `http://localhost:3000/api?topic=HTML`
In the query parameter called “topic” you can specify ANY topic you’d like the questions to relate to. (e.g, “HTML”)

**Expected result:** The page will display a JSON response with questions related to the specified topic. Following the previous example, `topic=HTML`, it should return questions about HTML.

**Comment by omiras** [comment]
@ekbalam11 Prueba las **test cases** del comentario anterior y danos feedback, gracias!

**Comment by ekbalam11** [comment]
> [@ekbalam11](https://github.com/ekbalam11) Prueba las **test cases** del comentario anterior y danos feedback, gracias!

He probado los test cases y mis comentarios son los siguientes:

1. Las instrucciones en los 3 casos son muy claras y las funcionalidades cumplen con los resultados esperados en todos los casos.

2. Mis únicos comentarios están en las instrucciones previas. Quizás parezca muy intuitivo, pero si hay una instrucción para iniciar los módulos de npm (npm install), considero que entonces para ser congruentes con ese nivel de detalle también sería bueno explicar que no existe el archivo .ENV en el que indican que el usuario debe agregar un API_KEY. Quizás indicando que se puede usar el .env.example sólo borrando .example podría funcionar. 

Hice el test siguiendo las instrucciones una a una al pie de la letra, y cuando yo inicié el app.js hubo error porque el número de puerto en el fichero .env no está definido. Yo creo que se resuelve con indicar en las instrucciones que es necesario escribir el PORT del usuario y quitar la declaración del PORT en el app.js, o no indicar nada, borrar la variable PORT del fichero .env,  y dejarlo en el puerto 3000 por default.

Son detalles muy pequeños, lo sé, pero intenté seguir este supuesto que se mencionó en clase de que muchas veces los usuarios no saben mucho del tema.

**Comment by omiras** [comment]
Gracias por las aportaciones @ekbalam11 

En efecto, siempre es interesante propcionar un .env.example indicando que variables de entorno necesita el programa, aunque aparezca bien documentado en el cóidog. Adicionalmente esa información puede ser añadida en el README con un escueto "You will need an Api Key from Gemini, you can get one here". De hecho, esta información también nos falta en nuestro repo principal!

Gracias a todas las partes por la implicación. Con estas dos aportaciones , si deseáis dejarlo documentado, podéis crear ambos ficheros .env.example y las instrucciones breves en README.

Testeado por @ekbalam11 creo que podemos dar la issue por testeada, ¡buen trabajo!

**Comment by omiras** [comment]
Hola,

Tras hablar con @crimanlor es verdad que el .env.example ya estaba presente en el repo, me confundí!
![Image](https://github.com/user-attachments/assets/6b95b5db-d814-42ad-ba24-91657fa7afe7)
